export const mapLocation = (name) => {
  const mappings = [
    ["Missiles (Billy Mays 1)", ""],
    ["Missiles (Billy Mays 2)", ""],
    ["Missiles (Gauntlet Right)", ""],
    ["Missiles (Gauntlet Left)", ""],
    ["Energy Tank (Gauntlet)", ""],
    ["Energy Tank (Terminator)", ""],
    ["Missiles (230)", ""],
    ["Power Bombs (Landing Site)", ""],
    ["Supers (Climb)", ""],
    ["Missiles (Alpha)", ""],
    ["Missiles (Beta)", ""],
    ["Power Bombs (Morph)", ""],
    ["Energy Tank (Brinstar Ceiling)", ""],
    ["Missiles (Moat)", ""],
    ["Morphing Ball", ""],
    ["Missiles (Mother Brain)", ""],
    ["Bombs", ""],
    ["Reserve Tank (Wrecked Ship)", ""],
    ["Missiles (Bowling)", ""],
    ["Energy Tank (Wrecked Ship)", ""],
    ["Gravity Suit", ""],
    ["Supers (WS Right)", ""],
    ["Supers (WS Left)", ""],
    ["Missiles (Sky)", ""],
    ["Missiles (Spooky)", ""],
    ["Missiles (Attic)", ""],
    ["Missiles (Ocean Bottom)", ""],
    ["Missiles (Ocean Middle)", ""],
    ["Varia Suit", ""],
    ["Energy Tank (Kraid)", ""],
    ["Missiles (Kraid)", ""],
    ["Space Jump", ""],
    ["Energy Tank (Ridley)", ""],
    ["Charge Beam", ""],
    ["Energy Tank (Waterway)", ""],
    ["Missiles (Watering Hole)", ""],
    ["Plasma Beam", ""],
    ["Spring Ball", ""],
    ["Missiles (Mickey Mouse)", ""],
    ["Power Bombs (Alpha)", ""],
    ["Missiles (Alpha PBs)", ""],
    ["Power Bombs (Beta)", ""],
    ["Grapple Beam", ""],
    ["Xray Scope", ""],
    ["Spazer", ""],
    ["Power Bombs (Crocomire)", ""],
    ["Energy Tank (Crocomire)", ""],
    ["Missiles (Cosine)", ""],
    ["Missiles (Indiana Jones)", ""],
    ["Missiles (Mainstreet)", ""],
    ["Supers (Crab)", ""],
    ["Energy Tank (Mama Turtle)", ""],
    ["Missiles (Mama Turtle)", ""],
    ["Supers (Watering Hole)", ""],
    ["Missiles (Beach)", ""],
    ["Power Bombs (Etecoons)", ""],
    ["Energy Tank (Etecoons)", ""],
    ["Supers (Etecoons)", ""],
    ["Supers (Spore Spawn)", ""],
    ["Missiles (Early Bridge)", ""],
    ["Supers (Early Bridge)", ""],
    ["Reserve Tank (Brinstar)", ""],
    ["Missiles (Brin Reserve 2)", ""],
    ["Missiles (Brin Reserve 1)", ""],
    ["Missiles (Big Pink)", ""],
    ["Missiles (Charge)", ""],
    ["Power Bombs (Mission Impossible)", ""],
    ["Missiles (Brin Tube)", ""],
    ["Energy Tank (Wave Gate)", ""],
    ["Missiles (Croc Escape)", ""],
    ["Energy Tank (Botwoon)", ""],
    ["Missiles (Aqueduct)", ""],
    ["Supers (Aqueduct)", ""],
    ["Missiles (Precious)", ""],
    ["Missiles (Cathedral)", ""],
    ["Missiles (Sand Pit Left)", ""],
    ["Reserve Tank (Maridia)", ""],
    ["Missiles (Sand Pit Right)", ""],
    ["Power Bombs (Sand Pit Right)", ""],
    ["Energy Tank (Firefleas)", ""],
    ["Ice Beam", ""],
    ["Missiles (Crumble Shaft)", ""],
    ["Missiles (GT)", ""],
    ["Supers (GT)", ""],
    ["Missiles (Maze)", ""],
    ["Power Bombs (Maze)", ""],
    ["HiJump Boots", ""],
    ["Missiles (HJB)", ""],
    ["Energy Tank (HJB)", ""],
    ["Reserve Tank (Norfair)", ""],
    ["Missiles (Norfair Reserve 2)", ""],
    ["Missiles (Norfair Reserve 1)", ""],
    ["Missiles (Bubble Mountain)", ""],
    ["Missiles (Speed)", ""],
    ["Speed Booster", ""],
    ["Missiles (Three Muskateers)", ""],
    ["Missiles (Wave)", ""],
    ["Wave Beam", ""],
    ["Power Bombs (Shame)", ""],
    ["Screw Attack", ""],
  ];

  const mapped = mappings.find((m) => m[0] == name);
  if (mapped != undefined) {
    if (mapped[1] == "") {
      return name;
    }
    return mapped[1];
  }
  throw new Error("missing " + name);
};
